version: '3'

services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "8161:8161"  # Porta web
      - "61616:61616"  # Porta do broker
      - "61613:61613" # Porta do STOMP
    environment:
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
    restart: always